### ISSUE TITLE
Issue with /tf Remapping in kinematic_icp for 2D LiDAR

### ISSUE THREAD

**Issue by MikeDegany** [PRBonn/kinematic-icp#23]
## Problem Summary  

I encountered an issue with the `kinematic_icp` package when running LiDAR odometry with a remapped `/tf` topic and `use_2d_lidar:=true`. In my setup, I remap `/tf` to `/JK3/tf` (JK3: namespace) to match my simulation environment. This configuration works correctly with default (3D LiDAR) version of the package. However, the node crashes with an error when using 2D LiDAR (`use_2d_lidar:=true`).

## Error Details  
When launching the `online_node` with the following command for 2D LiDAR odometry:  
```bash
ros2 launch kinematic_icp online_node.launch.py \
    lidar_topic:=/JK3/sensors/lidar2d_0/scan \ # replace JK3 with your namespace
    use_2d_lidar:=true \
    use_sim_time:=True
```
    
and remapping /tf to /JK3/tf in the launch file, I encounter the following error:

```bash
[ERROR] [kinematic_icp_online_node-1]: process has died 
[pid 288680, exit code -6, cmd '/[workspace]/install/kinematic_icp/lib/kinematic_icp/kinematic_icp_online_node --ros-args -r __node:=online_node -r __ns:=/kinematic_icp --params-file /[workspace]/install/kinematic_icp/share/kinematic_icp/config/kinematic_icp_ros.yaml --params-file /tmp/launch_params_23mw3z60 -r lidar_odometry:=lidar_odometry -r /tf:=/JK3/tf'].
```

When running the node without remapping /tf, the node does not crash but fails to find the required transforms, which prevents it from performing odometry (obviously).

However, when running the following command with 3D LiDAR odometry, everything works as expected, even with the same remapping:

```bash
ros2 launch kinematic_icp online_node.launch.py \
    lidar_topic:=/JK3/sensors/lidar3d_0/points \
    use_2d_lidar:=false \
    use_sim_time:=True
```
## Steps to Reproduce

1. Clone the latest version of the repository.
2. Configure a launch file to include the following remapping:

```py
remappings=[
    ('/tf', '/JK3/tf'), # replace JK3 with your namespace
],
```

3. Run the node with a 2D LiDAR topic (sensor_msgs/LaserScan) and the following parameters:
```bash
ros2 launch kinematic_icp online_node.launch.py \
    lidar_topic:=/JK3/sensors/lidar2d_0/scan \ # replace JK3 with your namespace
    use_2d_lidar:=true \
    use_sim_time:=True
```
4. ### MOVE THE ROBOT AND THE CODE CRASHES!

5. Run the node with a 3D LiDAR topic (sensor_msgs/PointCloud2) using the following parameters:
```bash
    ros2 launch kinematic_icp online_node.launch.py \
        lidar_topic:=/JK3/sensors/lidar3d_0/points \ # replace JK3 with your namespace
        use_2d_lidar:=false \
        use_sim_time:=True
```
6. Observe that the node runs without errors.

## Expected Behavior

The kinematic_icp node should support remapping /tf for both 2D and 3D LiDAR configurations. Alternatively, if remapping /tf is not supported in specific configurations, an explicit error message should be provided, and the limitation should be documented.

## Actual Behavior

**2D LiDAR (use_2d_lidar:=true):** The node crashes with a fatal error (exit code -6) when remapping /tf to /JK3/tf.
**3D LiDAR (use_2d_lidar:=false):** The node runs without issues, even with the same remapping.

## Environment Details

- **OS:** Ubuntu 22.04
- **ROS Version:** ROS2 Humble
- **kinematic_icp Version:** Latest commit as of Nov 29 2024.
- **LiDAR Configuration:**
2D LiDAR topic: /JK3/sensors/lidar2d_0/scan (sensor_msgs/LaserScan)
3D LiDAR topic: /JK3/sensors/lidar3d_0/points (sensor_msgs/PointCloud2)
- **Remapping:** /tf → /JK3/tf

## Proposed Solutions

- Investigate differences in handling sensor_msgs/LaserScan (2D LiDAR) and sensor_msgs/PointCloud2 (3D LiDAR) in relation to TF remapping.
- Add support for remapping /tf for 2D LiDAR configurations.
- Add support for namespacing in general
- Update documentation to clarify any limitations or requirements regarding `/tf` remapping for 2D LiDAR odometry.

## Additional Context

I tested this with both 2D and 3D LiDAR odometry. The issue is isolated to 2D LiDAR (sensor_msgs/LaserScan).

If needed, I can share additional logs, configuration files, or launch files to help reproduce the issue.

Thank you for maintaining this package! Please let me know if there's anything else I can provide to assist with debugging this problem.

**Comment by tizianoGuadagnino** [comment]
Hello @MikeDegany, I cannot reproduce the behavior you describe. Although it is not a standard practice to remap the `/tf` topic (99% of ROS packages expect the transforms to be under `/tf` and `/tf_static`), I really cannot see a difference between using the `PointCloud2` and `LaserScan` msg. Have you check the `frame_id` in the msg?

**Comment by MikeDegany** [comment]
Thank you for the response. After more checks, I found that the problem isn’t caused by namespacing. All topics in my setup are namespaced because I use multiple robots, and this setup works fine in other cases.

I checked the LaserScan messages, and the data looks correct. However, the node still crashes **just after I move the robot**, and I’m not sure how to debug this further. Do you have any suggestions for further investigation?

Would it be better to close this issue and open a new one later with more details or keep it until I resolve it? In the meantime, if you could [share](mailto:mike.degany@gmail.com) a `bag` file or provide details about the 2D LiDAR data you tested with, it might help me find the differences and fix the problem.

Thank you for your help!
