### ISSUE TITLE
about sample data availability

### ISSUE THREAD

**Issue by gisbi-kim** [PRBonn/kinematic-icp#25]
Dear authors, 

thanks for releasing this great open source to the community. 

I would like to introduce this paper to students and use this code for educational purposes in a SLAM lecture, 
I think this is a very great material for teaching the basics of robotics. I love to start with the mobile robot's basic things such as wheel kinematics and believe that is important.

For that reason, I am wondering if any sample bag files could be publicly provided. (of course, I prefer the one used in the paper)

**Comment by benemer** [comment]
Thank you very much! That's a great idea. We can not release the company's data, but we can send you a bag from our Husky platform. I will contact you via email :)

**Comment by sehb** [comment]
Please send  the bag to me too!  Thanks! 
seuhust@gmail.com

**Comment by MikeDegany** [comment]
Dear @benemer I would appreciate it if you could share your bag file with me as well. Thanks. Mike.Degany@gmail.com

**Comment by omerssid** [comment]
Dear @benemer, I am having issues getting the package to work so I would appreciate it if you could send me the sample bag. thanks in advance! omerseyyidd@gmail.com

**Comment by benemer** [comment]
Sure. I will upload it on our server and then add a link to the Readme because so many people have asked now.

**Comment by benemer** [comment]
See https://github.com/PRBonn/kinematic-icp/pull/29
